---
- name: Beats Installation
  include_tasks: "{{ansible_distribution_file_variety}}.yml"

- name: Configure Index Lifecycle Management for filebeat
  copy:
    src: ilm.json
    dest: /etc/filebeat/ilm.json
  notify:
  - Restart filebeat

- name: Configure Index Lifecycle Management for metricbeat
  copy:
    src: ilm.json
    dest: /etc/metricbeat/ilm.json
  notify:
  - Restart metricbeat

- name: Configure Filebeat
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  notify:
  - Restart filebeat

- name: Configure Metricbeat
  template:
    src: metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
  notify:
  - Restart metricbeat

